package fresh;

public enum Status {
    OK,
    USUARIO_REPETIDO,
    PAGO_INCORRECTO,
    NOMBRE_INVALIDO,
    NOMBRE_AUTOR_INVALIDO,
    CONTRASENA_INVALIDA,
    EDAD_INVALIDA,
    MP3_INVALIDO,
    CANCION_REPETIDA,
    ALBUM_REPETIDO,
    ERROR_GUARDAR,
    ERROR_CARGAR,
    OPERACION_INACCESIBLE
}