package fresh;

public enum Status {
    OK,
    USUARIO_REPETIDO,
    PAGO_INCORRECTO,
    FALTA_NOMBRE,
    FALTA_NOMBRE_AUTOR,
    FALTA_CONTRASEÑA,
    EDAD_INCORRECTA,
    MP3_INVALIDO,
    CANCION_REPETIDA,
    ALBUM_REPETIDO,
    ERROR_GUARDAR,
    ERROR_CARGAR
}