package fresh;

public enum Status {
    OK,
    USUARIO_REPETIDO,
    PAGO_INCORRECTO,
    NOMBRE_INVALIDO,
    NOMBRE_AUTOR_INVALIDO,
    CONTRASENA_INVALIDA,
    EDAD_INVALIDA,
    FICHERO_INVALIDO,
    USUARIO_BLOQUEADO,
    MP3_INVALIDO,
    CANCION_REPETIDA,
    ALBUM_VACIO,
    ALBUM_REPETIDO,
    LISTA_REPRODUCCION_REPETIDA,
    ELEMENTO_REPETIDO,
    DESCRIPCION_INVALIDA,
    CANCION_NO_MODIFICABLE,
    CANCION_NO_REPORTABLE,
    CONFIGURACION_INVALIDA,
    ERROR_GUARDAR,
    ERROR_CARGAR,
    OPERACION_INACCESIBLE
}