package fresh.datos.tipos;

public enum EstadoCancion {
   PENDIENTE_VALIDACION,
   VALIDADA,
   VALIDADA_EXPLICITA,
   RECHAZADA_REVISABLE,
   BLOQUEADA_TEMPORAL,
   BLOQUEADA_TEMPORAL_EXPLICITA,
   BOQUEADA_PERMANENTE
}